### ISSUE TITLE
Всратое ТЗ по телеграм-боту

### ISSUE THREAD

**Issue by vas3k** [Birdi7/vas3k.club-bot#1]
По сути у бота две задачи: 

1. Оповещать человеков. С этим справляются триггеры джанги и сам движок Клуба, тут проблем нет
2. Выполнять команды. Вот ради этого мы тут и устроили всю вечеринку

Вторая часть бота должна быть отдельным сервисом, который общается с Клубом через некий API. Я пока не знаю как точно будет выглядеть аутентификация-авторизация таких запросов, но пока оно и не важно. Пока абстрагируем логику общения с API в отдельный класс и потом всю ее реализуем.

На данный момент бот должен выполнять следующие команды:

1. /start и авторизация юзера. По коду или кликом по ссылке, не суть важно. Главное чтобы бот реагировал на команду /start и просил авторизации, если юзер ему не известен.
2. Админка. Критически важная часть. Именно через бота модераторы Клуба впускают-реджектят новых юзеров и одобряют-неодобряют посты. По сути это реакции на callback action'ы. Вот тут можно посмотреть список: https://github.com/vas3k/vas3k.club/blob/master/bot/handlers/moderator.py#L156
3. Ответы на комменты. Самая важная и часто используемая часть бота. Делается обычным реплаем на сообщение-коммент. Без всяких команд. Неочевидная деталь здесь — реплай на коммент может работать в любом чате, куда добавлен бот, не только в личной переписке с пользователем. Хотелось бы это так и оставить. Вот код как оно работает сейчас: https://github.com/vas3k/vas3k.club/blob/master/bot/handlers/replies.py
4. Постинг постов и ссылок. Штука экспериментальная и мы пока не знаем нужна ли она вообще. Сейчас она работает без команды, но было бы удобнее все-таки сделать команды типа /new_post и /new_link. Дальше обычно начинается флоу из диалога: «введите заголовок поста», «введите описание поста» и «готовы постить?». Пока всё. Дальше посмотрим надо ли оно кому. Сейчас там полная лапша (ибо нет стейтов), её можно смело выбрасывать и сделать своё простое https://github.com/vas3k/vas3k.club/blob/master/bot/handlers/personal.py

Ну и из ближайших планов: 

1. Было бы круто добавить под комментарии кнопки «лайк», «посмотреть» и «ответить» (просто открывает форму реплая на сообщение в телеграме)
2. Хочется команду /top, которая бы возвращала топ постов за неделю. API допилим для этого.
3. Команда, возвращающая гороскоп, не помешала бы :D

Ну и да, всё это должно крутиться в докере с docker-compose и слушать вебсокет на разрешенном порту. Скорее всего сделаем боту отдельный поддомен.

**Comment by Birdi7** [comment]
Учитывая хорошую декомпозцию от @vas3k, разбивать задачи почти и не надо

- [x] #2 Скелет бота. Так как бы больше не можем ходить в базу Клуба, нужно будет завести свою базу данных, которая будет сервисом в compose. Под это планирую использовать postgresql, ходить будем через [sqlalchemy](https://www.sqlalchemy.org/), и [alembic](https://alembic.sqlalchemy.org/en/latest/) для миграций. Стек обсуждаемый, вдохновлялся [этим](https://github.com/aiogram/bot/) ботом. Единственное, что вместо pipenv используется [poetry](https://python-poetry.org/) - почему нет?

- [ ] #3 Реализация команды `/start`. Для начала достаточно первого пункта, потому как второй пункт это уже улучшение текущего функционала
    - [ ] Userflow: пользователь нажал старт -> бот попросил код авторизации -> юзер отправил код -> бот отправил запросу клубу, подтвердил. Текущий код лежит в [personal.process_auth](https://github.com/vas3k/vas3k.club/blob/master/bot/handlers/personal.py#L21)
    - [ ] Userflow: пользователь нажал кнопку на фронте -> боту пришел старт с кодом. Для этого нужно диплинкинг в боте. Есть [пример](https://github.com/aiogram/aiogram/blob/dev-2.x/examples/regexp_commands_filter_example.py#L10)
- [ ] #4 Админка. Очень массивный функционал в плане апишки Клуба, которой сейчас нет. Поэтому
    - [ ] Костяк бота. 
        - [ ] Отправка инлайн клавы. [Пример](https://github.com/aiogram/aiogram/blob/dev-2.x/examples/callback_data_factory_simple.py#L29). Для генерации колбеков используется фабрика [CallbackData](https://github.com/aiogram/aiogram/blob/dev-2.x/examples/callback_data_factory_simple.py#L24), это хорошая практика. **Вопрос**: в какой именно момент она отправляется? В коде Клуба найти не смог. Подозреваю, что из основного бэка где-то триггерится телеграм напрямую. В первой версии можно оставить, потому как так легче, и придется соблюдать текущий формат callback query, но в будущем хорошо бы сделать через апишку
        - [ ] Обработка входящих колбеков. Список см. [moderator.py](https://github.com/vas3k/vas3k.club/blob/master/bot/handlers/moderator.py#L156). Каждая функция переносится в `callback_query_handler`. [Пример](https://github.com/aiogram/aiogram/blob/dev-2.x/examples/callback_data_factory_simple.py#L41) реализации. 
    - [ ] Апишка клуба. Нужна для каждого экшена модераторов. 5 типов экшенов, пять апишек. Логику оставим на бэке, со стороны бота просто триггерим апи ручки. Банально,
      - [ ] Approve post 
      - [ ] Forgive post
      - [ ] Delete post
      - [ ] Approve user
      - [ ] Reject user. **Note**: with reasons
- [ ] #5 Реплай. Переносится почти 1 в 1, и снова с апишкой
    - [ ] Обработка реплаев. Изян, функция регистрируется через `@dp.message_handler(is_reply=True, chat_type=[ChatType.PRIVATE, ChatType.GROUP, ChatType.SUPER_GROUP]`. В функцию будет подан аргумент `reply`, в котором будет лежать сообщение, на которое ответили. Написано это все [тут](https://github.com/aiogram/aiogram/blob/dev-2.x/aiogram/dispatcher/filters/builtin.py#L687)
     - [ ] Апишка по созданию комментов. Должна позволить реализовать то, что сейчас делается напрямую. См. [replies.py](https://github.com/vas3k/vas3k.club/blob/master/bot/handlers/replies.py)
- [ ] #6 Постинг 
  - [ ] Апишка для создания новых постов/ссылок
  - [ ] Сам диалог. Примерная реализация [есть](https://github.com/Birdi7/vas3k.club-bot/blob/master/app/handlers/create_post.py), нужно допилить
- [ ] #7 Обертка бота 
  - [ ] Для разработки максимально удобно использовать polling, а не webhook. [Описание](https://stackoverflow.com/a/40036596). Aiogram умеет в генерацию сертификата, поэтому с точки зрения реализации меняется мало. См. [пример](https://github.com/aiogram/aiogram/blob/dev-2.x/examples/webhook_example.py)
  - [ ] Dockerfile. [Есть](https://github.com/Birdi7/vas3k.club-bot/blob/master/dockerfile), но нужно допилить под вебхук
  - [ ] docker-compose config. То, что сейчас лежит в репе - гавно, нужно переписать

## Источники информации по тому, как пользоваться библиотекой aiogram
- собственно, [дока](https://docs.aiogram.dev/en/latest/?badge=latest)
- дока частно не помогает, но помогают [примеры](https://github.com/aiogram/aiogram/tree/dev-2.x/examples)
- если и примеры не помогают, есть чат [@aiogram_ru](https://t.me/aiogram_ru)
